import { Link, Navigate } from "react-router-dom";
import { FiBookmark, FiCompass, FiGrid, FiShield, FiSliders } from "react-icons/fi";
import { useAuth } from "../context/useAuth";
const Dashboard = () => {
  const { user, isAuthenticated, isLoading } = useAuth();
  if (!isLoading && !isAuthenticated) return <Navigate to="/login" replace />;
  if (isLoading) return <div className="min-h-[55vh] animate-pulse" />;
  const cards = [["Explore catalog", "Find the right device with focused filters.", "/devices", <FiCompass className="text-2xl text-sky-500" />], ["Start a comparison", "Compare up to three models side by side.", "/compare", <FiSliders className="text-2xl text-sky-500" />], ["Your library", "Return to favorites and saved decisions.", "/library", <FiBookmark className="text-2xl text-sky-500" />]];
  return <section className="space-y-8"><div className="relative overflow-hidden rounded-[30px] border border-sky-200 bg-gradient-to-br from-sky-100 via-white to-cyan-50 p-8 dark:border-sky-500/20 dark:from-slate-800 dark:via-slate-900 dark:to-sky-950/40 md:p-12"><div className="absolute -right-10 -top-10 h-52 w-52 rounded-full bg-sky-400/20 blur-3xl" /><p className="text-sm font-bold uppercase tracking-[0.24em] text-sky-600 dark:text-sky-300">Your decision workspace</p><h1 className="mt-3 text-4xl font-black tracking-tight text-slate-900 dark:text-white">Welcome back, {user?.name?.split(" ")[0]}.</h1><p className="mt-3 max-w-xl text-slate-600 dark:text-slate-300">Build a shortlist, compare with confidence, and keep every strong contender within reach.</p><Link to="/devices" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-sky-500 px-5 py-3 font-bold text-slate-950 transition hover:bg-sky-400">Browse devices <FiCompass /></Link></div><div className="grid gap-5 md:grid-cols-3">{cards.map(([title, description, to, icon]) => <Link key={title} to={to} className="group rounded-2xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-sky-400/50 hover:shadow-xl dark:border-slate-700 dark:bg-slate-800/70">{icon}<h2 className="mt-5 text-lg font-bold text-slate-900 dark:text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{description}</p></Link>)}</div><div className="grid gap-4 rounded-2xl border border-slate-200 bg-white/70 p-6 sm:grid-cols-2 dark:border-slate-700 dark:bg-slate-800/50"><div><FiGrid className="text-sky-500" /><p className="mt-2 font-bold">Personal library</p><p className="text-sm text-slate-500">Favorites and comparisons persist across sessions.</p></div><div><FiShield className="text-sky-500" /><p className="mt-2 font-bold">Secure sessions</p><p className="text-sm text-slate-500">Sign out or change your password to revoke active access.</p></div></div></section>;
};
export default Dashboard;
