create table if not exists public.devices (
  id text primary key,
  brand text not null,
  model text not null,
  category text,
  price numeric,
  payload jsonb not null
);

create index if not exists idx_devices_brand on public.devices (brand);
create index if not exists idx_devices_category on public.devices (category);
create index if not exists idx_devices_catalog_search on public.devices (brand, model, id);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_users_email on public.users (email);

create table if not exists public.user_sessions (id uuid primary key, user_id bigint not null references public.users(id) on delete cascade, token_hash text not null unique, expires_at timestamptz not null, revoked_at timestamptz, created_at timestamptz not null default now());
create index if not exists idx_user_sessions_active on public.user_sessions (user_id, expires_at) where revoked_at is null;
create table if not exists public.user_favorites (user_id bigint not null references public.users(id) on delete cascade, device_id text not null references public.devices(id) on delete cascade, created_at timestamptz not null default now(), primary key (user_id, device_id));
create table if not exists public.saved_comparisons (id uuid primary key, user_id bigint not null references public.users(id) on delete cascade, name text not null, device_ids jsonb not null, created_at timestamptz not null default now());
